name: Deploy content to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - ./**/*
      - .github/workflows/**
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare deploy directory
        run: |
          mkdir deploy-root
          shopt -s extglob
          mv -- !(deploy-root) deploy-root/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy-root
      - name: Deploy content to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
